/** @brief Tests of Hooke's law */
// Generated by GitHub Copilot (Grok Code Fast 1); reviewed by Eike Mueller
#ifndef TEST_HOOKE_HH
#define TEST_HOOKE_HH TEST_HOOKE_HH
#include <random>
#include <string>
#include <algorithm>
#include "hooke.hh"
#include <gtest/gtest.h>

/** @brief Class for testing Hooke's law
 *
 * Generated by GitHub Copilot (Grok Code Fast 1); reviewed by Eike Mueller
 */
class HookeTest : public ::testing::TestWithParam<std::string>
{
public:
    /** @brief Constructor
     * Create a new instance */
    HookeTest() {}

protected:
    /** @brief initialise test parameters */
    void SetUp() override
    {
        if (GetParam() == "even")
        {
            grid_spec.nx = 16;
            grid_spec.ny = 8;
            grid_spec.nz = 4;
        }
        else
        {
            grid_spec.nx = 17;
            grid_spec.ny = 13;
            grid_spec.nz = 7;
        }
        grid_spec.Lx = 1.2;
        grid_spec.Ly = 1.1;
        grid_spec.Lz = 0.7;
        tolerance = 1.E-6;
        rng.seed(7812481);
    }

    /** @brief Test that isotropic and anisotropic stress computation agree for isotropic material
     *
     * Generated by GitHub Copilot (Grok Code Fast 1); reviewed by Eike Mueller
     */
    void test_hooke()
    {
        size_t nvoxels = grid_spec.number_of_voxels();

        // Generate random epsilon
        float *epsilon = nullptr;
        CUDA_CHECK(cudaMallocHost(&epsilon, 6 * nvoxels * sizeof(float)));
        std::generate(epsilon, epsilon + 6 * nvoxels, [&]()
                      { return distribution(rng); });

        // Generate random lambda and mu
        float *lambda = nullptr;
        float *mu = nullptr;
        CUDA_CHECK(cudaMallocHost(&lambda, nvoxels * sizeof(float)));
        CUDA_CHECK(cudaMallocHost(&mu, nvoxels * sizeof(float)));
        std::generate(lambda, lambda + nvoxels, [&]()
                      { return 0.5f + distribution(rng); });
        std::generate(mu, mu + nvoxels, [&]()
                      { return 0.5f + distribution(rng); });

        // Construct stiffness tensor for isotropic material
        float *stiffness = nullptr;
        CUDA_CHECK(cudaMallocHost(&stiffness, 21 * nvoxels * sizeof(float)));
        for (size_t ell = 0; ell < nvoxels; ++ell)
        {
            float lambda_ell = lambda[ell];
            float mu_ell = mu[ell];
            stiffness[0 * nvoxels + ell] = 2 * mu_ell + lambda_ell; // C00
            stiffness[1 * nvoxels + ell] = 2 * mu_ell + lambda_ell; // C11
            stiffness[2 * nvoxels + ell] = 2 * mu_ell + lambda_ell; // C22
            stiffness[3 * nvoxels + ell] = mu_ell;                  // C33
            stiffness[4 * nvoxels + ell] = mu_ell;                  // C44
            stiffness[5 * nvoxels + ell] = mu_ell;                  // C55
            stiffness[6 * nvoxels + ell] = lambda_ell;              // C01
            stiffness[7 * nvoxels + ell] = lambda_ell;              // C02
            stiffness[8 * nvoxels + ell] = lambda_ell;              // C12
            // Others are zero
            for (int i = 9; i < 21; ++i)
                stiffness[i * nvoxels + ell] = 0.0f;
        }

        // Allocate device memory
        float *dev_epsilon = nullptr;
        float *dev_sigma_iso = nullptr;
        float *dev_sigma_aniso = nullptr;
        float *dev_lambda = nullptr;
        float *dev_mu = nullptr;
        float *dev_stiffness = nullptr;
        CUDA_CHECK(cudaMalloc(&dev_epsilon, 6 * nvoxels * sizeof(float)));
        CUDA_CHECK(cudaMalloc(&dev_sigma_iso, 6 * nvoxels * sizeof(float)));
        CUDA_CHECK(cudaMalloc(&dev_sigma_aniso, 6 * nvoxels * sizeof(float)));
        CUDA_CHECK(cudaMalloc(&dev_lambda, nvoxels * sizeof(float)));
        CUDA_CHECK(cudaMalloc(&dev_mu, nvoxels * sizeof(float)));
        CUDA_CHECK(cudaMalloc(&dev_stiffness, 21 * nvoxels * sizeof(float)));

        // Copy data to device
        CUDA_CHECK(cudaMemcpy(dev_epsilon, epsilon, 6 * nvoxels * sizeof(float), cudaMemcpyHostToDevice));
        CUDA_CHECK(cudaMemcpy(dev_lambda, lambda, nvoxels * sizeof(float), cudaMemcpyHostToDevice));
        CUDA_CHECK(cudaMemcpy(dev_mu, mu, nvoxels * sizeof(float), cudaMemcpyHostToDevice));
        CUDA_CHECK(cudaMemcpy(dev_stiffness, stiffness, 21 * nvoxels * sizeof(float), cudaMemcpyHostToDevice));

        // Compute stress isotropic
        compute_stress_isotropic(dev_epsilon, dev_sigma_iso, dev_lambda, dev_mu, grid_spec);
        CUDA_CHECK(cudaDeviceSynchronize());

        // Compute stress anisotropic
        compute_stress_anisotropic(dev_epsilon, dev_sigma_aniso, dev_stiffness, grid_spec);
        CUDA_CHECK(cudaDeviceSynchronize());

        // Copy back to host
        float *sigma_iso = nullptr;
        float *sigma_aniso = nullptr;
        CUDA_CHECK(cudaMallocHost(&sigma_iso, 6 * nvoxels * sizeof(float)));
        CUDA_CHECK(cudaMallocHost(&sigma_aniso, 6 * nvoxels * sizeof(float)));
        CUDA_CHECK(cudaMemcpy(sigma_iso, dev_sigma_iso, 6 * nvoxels * sizeof(float), cudaMemcpyDeviceToHost));
        CUDA_CHECK(cudaMemcpy(sigma_aniso, dev_sigma_aniso, 6 * nvoxels * sizeof(float), cudaMemcpyDeviceToHost));

        // Check relative difference
        float rel_diff = relative_difference(sigma_iso, sigma_aniso, 6 * nvoxels);
        EXPECT_NEAR(rel_diff, 0.0, tolerance);

        // Free memory
        CUDA_CHECK(cudaFree(dev_epsilon));
        CUDA_CHECK(cudaFree(dev_sigma_iso));
        CUDA_CHECK(cudaFree(dev_sigma_aniso));
        CUDA_CHECK(cudaFree(dev_lambda));
        CUDA_CHECK(cudaFree(dev_mu));
        CUDA_CHECK(cudaFree(dev_stiffness));
        CUDA_CHECK(cudaFreeHost(epsilon));
        CUDA_CHECK(cudaFreeHost(lambda));
        CUDA_CHECK(cudaFreeHost(mu));
        CUDA_CHECK(cudaFreeHost(stiffness));
        CUDA_CHECK(cudaFreeHost(sigma_iso));
        CUDA_CHECK(cudaFreeHost(sigma_aniso));
    }

    /* Class variables */
    /** @brief grid specification */
    GridSpec grid_spec;
    /** @brief tolerance */
    float tolerance;
    /** @brief random number generator */
    std::default_random_engine rng;
    /** @brief random number distribution used for initialisation */
    std::normal_distribution<float> distribution;
};

INSTANTIATE_TEST_SUITE_P(Hooke, HookeTest, testing::Values("even", "odd"));

/** @brief Check that isotropic and anisotropic Hooke's law agree for isotropic material */
TEST_P(HookeTest, TestHooke) { test_hooke(); }

#endif // TEST_HOOKE_HH