/** @brief Implementation of hooke.hh */
// Generated by GitHub Copilot (Grok Code Fast 1)
#include "hooke.hh"

/* Kernel for computing stress sigma_{ij} = C_{ijkl} epsilon_{kl} with
 *
 *     C_{ijkl} = lambda*delta_{ij}delta_{kl} + mu*(delta_{ik}delta_{jl}+delta_{il}delta_{jk})
 */
__global__ void compute_stress_isotropic_kernel(float *__restrict__ dev_epsilon,
                                                float *__restrict__ dev_sigma,
                                                float *__restrict__ dev_lambda,
                                                float *__restrict__ dev_mu,
                                                const size_t nvoxels)
{
  int ell = blockDim.x * blockIdx.x + threadIdx.x;
  if (ell < nvoxels)
  {
    float lambda = dev_lambda[ell];
    float mu = dev_mu[ell];
    float tr_epsilon = dev_epsilon[ell] + dev_epsilon[nvoxels + ell] + dev_epsilon[2 * nvoxels + ell];
    for (int alpha = 0; alpha < 3; ++alpha)
    {
      int idx = alpha * nvoxels + ell;
      dev_sigma[idx] = 2 * mu * dev_epsilon[idx] + lambda * tr_epsilon;
    }
    for (int alpha = 3; alpha < 6; ++alpha)
    {
      int idx = alpha * nvoxels + ell;
      dev_sigma[idx] = 2 * mu * dev_epsilon[idx];
    }
  }
}

/* Kernel for computing stress sigma_{ij} = C_{ijkl} epsilon_{kl} for anisotropic material */
__global__ void compute_stress_anisotropic_kernel(float *__restrict__ dev_epsilon,
                                                  float *__restrict__ dev_sigma,
                                                  float *__restrict__ dev_stiffness,
                                                  const size_t nvoxels)
{
  int ell = blockDim.x * blockIdx.x + threadIdx.x;
  if (ell < nvoxels)
  {
    // Load stiffness tensor components
    float C[21];
    for (int i = 0; i < 21; ++i)
      C[i] = dev_stiffness[i * nvoxels + ell];

    // Load epsilon components
    float eps[6];
    for (int i = 0; i < 6; ++i)
      eps[i] = dev_epsilon[i * nvoxels + ell];

    // Compute sigma
    dev_sigma[0 * nvoxels + ell] = C[0] * eps[0] + C[6] * eps[1] + C[7] * eps[2] + 2 * C[9] * eps[3] + 2 * C[10] * eps[4] + 2 * C[11] * eps[5];
    dev_sigma[1 * nvoxels + ell] = C[1] * eps[1] + C[6] * eps[0] + C[8] * eps[2] + 2 * C[12] * eps[3] + 2 * C[13] * eps[4] + 2 * C[14] * eps[5];
    dev_sigma[2 * nvoxels + ell] = C[2] * eps[2] + C[7] * eps[0] + C[8] * eps[1] + 2 * C[15] * eps[3] + 2 * C[16] * eps[4] + 2 * C[17] * eps[5];
    dev_sigma[3 * nvoxels + ell] = 2 * C[3] * eps[3] + C[9] * eps[0] + C[12] * eps[1] + C[15] * eps[2] + 2 * C[18] * eps[4] + 2 * C[19] * eps[5];
    dev_sigma[4 * nvoxels + ell] = 2 * C[4] * eps[4] + C[10] * eps[0] + C[13] * eps[1] + C[16] * eps[2] + 2 * C[18] * eps[3] + 2 * C[20] * eps[5];
    dev_sigma[5 * nvoxels + ell] = 2 * C[5] * eps[5] + C[11] * eps[0] + C[14] * eps[1] + C[17] * eps[2] + 2 * C[19] * eps[3] + 2 * C[20] * eps[4];
  }
}

/* Compute stress sigma_{ij} = C_{ijkl} epsilon_{kl} for isotropic material */
void compute_stress_isotropic(float *__restrict__ dev_epsilon,
                              float *__restrict__ dev_sigma,
                              float *__restrict__ dev_lambda,
                              float *__restrict__ dev_mu,
                              const GridSpec grid_spec)
{
  size_t nvoxels = grid_spec.number_of_voxels();
  const size_t nblocks = (nvoxels + BLOCKSIZE - 1) / BLOCKSIZE;
  compute_stress_isotropic_kernel<<<nblocks, BLOCKSIZE>>>(dev_epsilon, dev_sigma,
                                                          dev_lambda, dev_mu, nvoxels);
}

/* Compute stress sigma_{ij} = C_{ijkl} epsilon_{kl} for anisotropic material */
void compute_stress_anisotropic(float *__restrict__ dev_epsilon,
                                float *__restrict__ dev_sigma,
                                float *__restrict__ dev_stiffness,
                                const GridSpec grid_spec)
{
  size_t nvoxels = grid_spec.number_of_voxels();
  const size_t nblocks = (nvoxels + BLOCKSIZE - 1) / BLOCKSIZE;
  compute_stress_anisotropic_kernel<<<nblocks, BLOCKSIZE>>>(dev_epsilon, dev_sigma,
                                                            dev_stiffness, nvoxels);
}