/** @brief Hooke's law for isotropic and anisotropic materials */
#ifndef HOOKE_HH
#define HOOKE_HH HOOKE_HH

#include "common.hh"

/** @brief Compute stress from strain for isotropic material
 *
 * Given epsilon and spatially varying Lame parameters lambda, mu compute the
 * stress sigma according to sigma_{ij} = C_{ijkl} epsilon_{kl} where
 *
 *      C_{ijkl} = lambda*delta_{ij}delta_{kl} + mu*(delta_{ik}delta_{jl}+delta_{il}delta_{jk})
 * 
 * Generated by GitHub Copilot (Grok Code Fast 1); reviewed by Eike Mueller
 *
 * @param[in] dev_epsilon strain epsilon in real space (device array, size 6*nvoxels)
 * @param[out] dev_sigma resulting stress sigma in real space (device array, size 6*nvoxels)
 * @param[in] dev_lambda Lame parameter lambda (device array, size nvoxels)
 * @param[in] dev_mu Lame parameter mu (device array, size nvoxels)
 * @param[in] grid_spec specification of computational grid
 */
void compute_stress_isotropic(float *__restrict__ dev_epsilon,
                              float *__restrict__ dev_sigma,
                              float *__restrict__ dev_lambda,
                              float *__restrict__ dev_mu,
                              const GridSpec grid_spec);

/** @brief Compute stress from strain for anisotropic material
 *
 * Given epsilon and spatially varying stiffness tensor, compute the
 * stress sigma according to sigma_{ij} = C_{ijkl} epsilon_{kl}
 * 
 * Generated by GitHub Copilot (Grok Code Fast 1); reviewed by Eike Mueller
 *
 * @param[in] dev_epsilon strain epsilon in real space (device array, size 6*nvoxels)
 * @param[out] dev_sigma resulting stress sigma in real space (device array, size 6*nvoxels)
 * @param[in] dev_stiffness stiffness tensor (device array, size 21*nvoxels)
 * @param[in] grid_spec specification of computational grid
 */
void compute_stress_anisotropic(float *__restrict__ dev_epsilon,
                                float *__restrict__ dev_sigma,
                                float *__restrict__ dev_stiffness,
                                const GridSpec grid_spec);

#endif // HOOKE_HH